name: food_diary
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  uuid: ^4.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.2
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  fl_chart: ^0.68.0
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  bloc_test: ^9.1.0
  sqflite_common_ffi: ^2.3.5

flutter:
  uses-material-design: true
